name: Update CloudFlare Edge Locations data

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

  #schedule:
    # Run every hour in the 30th minute
    #- cron:  '30 * * * *'

jobs:

  gather_data:
    name: Gather the latest CloudFlare Edge Locations data
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install DuckDB and download data
        id: installDuckDB
        run: |
          npm run install-duckdb
          npm run download

      - name: Generate data and check for changes
        id: gatherData
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install dependencies
          npm i

          # Gather data
          npm run generate

          # Setup git repo
          git config --global user.name 'TobiLG'
          git config --global user.email 'tobilg@users.noreply.github.com'
          git remote set-url --push origin https://tobilg:$GITHUB_TOKEN@github.com/tobilg/cloudflare-edge-locations

          # Add new files if there are any
          git add .

          # Check for changes and commit if there are any
          git diff-index --cached --quiet HEAD || echo '::set-output name=changed::true'

      - name: Eventually commit and push new data
        if: ${{ steps.gatherData.outputs.changed == 'true' }}
        run: |
          # Increase package patch version
          npm --no-git-tag-version version patch

          # Add new files
          git add .

          # Commit changes
          git commit -am "[no ci] Data update on $(date '+%FT%H:%M:%S')"

          # Push to repo
          git push